effect @a[tag=cat] jump_boost 600 1 true
effect @a[tag=cat] strength 600 20 true
effect @a[tag=cat] speed 600 1 true
give @a[tag=cat] spyglass
give @a[tag=cat] ender_pearl 32
give @a[tag=cat] snowball 16
give @a[tag=cat] bow
give @a[tag=cat] firework_rocket 32 3
give @a[tag=cat] arrow 32 39
replaceitem entity @a[tag=cat] slot.armor.head 1 turtle_helmet
replaceitem entity @a[tag=cat] slot.armor.chest 1 elytra
